#!/bin/bash
# /etc/init.d/startBot

### BEGIN INIT INFO
# Provides:          Robot
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start a Robot at init
# Description:       Script to start Robot at boot time
### END INIT INFO

# If you want a command to always run, put it here
# Carry out specific functions when asked to by the system 
case "$1" in
  start)
    echo  "Starting Robot"
      # run application you want to start
      clear
      echo  "ROS2 Removing old shit ... "
      rm -r ${PWD%}/ros2/build
      rm -r ${PWD%}/ros2/log
      rm -r ${PWD%}/ros2/install
      sleep 2 && clear 

      clear && cd ${PWD%}/ros2    
      echo  "ROS2 Building new stuff ... "
      colcon build
      echo  "ROS2 Build successful ... "
      sleep 2 && clear && cd ..
       
      echo  "ROS2 Sourcing ... "
      source ~/ros2_dashing/ros2-linux/setup.bash
      source "${PWD%}/ros2/install/setup.bash"
      source "${PWD%}/configs/local_env_vars.sh"

      sleep 2 && clear
      echo  "ROS2 launching ... "
      ros2 launch "${PWD%}/configs/bot_local.launch.py"
    ;;
  stop)
    echo "Stopping Robot"
    # kill application you want to stop
    for i in $( rosnode list ); do
      ros2 lifecycle set $i shutdown;
    done
    ;;
  *)
    echo "Usage: /etc/init.d/Robot {start|stop}"
    exit 1
    ;;
esac

exit 0
