version: "3.7"
services:
  balena-cli:
    build:
      context: .
      dockerfile: Dockerfile

    user: "ada"
    working_dir: /home/ada

    ports:
      # - "0.0.0.0:8080:8080/tcp"
      - 0.0.0.0:4567:4567/tcp
      
    init: true

    environment: 
      - DISPLAY
      - QT_X11_NO_MITSHM=1

    volumes:
      - ../balena_cli_configs:/home/ada/.balena
      # - ./ssh-keys:/home/node/.ssh
      # - ./scripts:/home/node/scripts
      # - ./staged-releases:/home/node/staged-releases
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock

      # Enable GUI environments
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    # Add devices to be share in container
    devices: 
      - /dev/ttyACM0
      # - /dev/video0
      # - /dev/video1
      # - /dev/video2
      # - /dev/video3
      # - /dev/video4
      # - /dev/video5
      # ...
      # - /dev/video*

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity 
    stdin_open: true
    tty: true

    command: "/bin/bash" 